  - name: copy mongodb repo file
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/
  - name: install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
  - name: start and enable mongodb service
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: start and enable mongodb service
    ansible.builtin.service:
      name: mongod
      state: restarted

