  - name: copy mongodb repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/
  - name: Install mongodb client
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: present

  - name: Load schema
    ansible.builtin.shell: mongo --host mongodb.nareshdevops.online < /app/schema/{{component}}.js