- name: copy {{components}} service file
  ansible.builtin.copy:
    src: "{{components}}.service"
    dest: /etc/systemd/system/
  when: 
    - {{component}} != "redis"
    - {{component}} != "mongodb"
    - {{component}} != "mysql"
    - {{component}} != "rabbitmq"
    - {{component}} != "web"
- name: reload, enable and start "{{component}}" service
  ansible.builtin.systemd_service:
    state: started
    daemon_reload: true
    enabled: yes
    name: "{{component}}"