- name: copy {{component}} service file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/
  when:
    - component != "redis"
    - component != "web"
- name: reload, enable and start {{component}} service
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    enabled: yes
    name: "{{component}}"
