  - name: Install and setup Nodejs
    ansible.builtin.import_role:
      name: common
      tasks_from: Nodejs_Setup
  - name: Application setup
    ansible.builtin.import_role:
      name: common
      tasks_from: app_setup
  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app/
  - name: load schema into mongo
    ansible.builtin.import_role:
      name: common
      tasks_from: load_mongo_schema
  - name: copy,reload,start and enable service
    ansible.builtin.import_role:
      name: common
      tasks_from: service_en&start
  

  
