  - name: install redis repo
    ansible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present
      disable_gpg_check: true
  - name: enable 6.2 version
    ansible.builtin.command: yum module enable redis:remi-6.2 -y
  - name:
    ansible.builtin.yum:
      name: redis
      state: present
  - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis.conf
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: start and enable service
    ansible.builtin.import_role:
      name: common
      tasks_from: service_en&start
