  - name: Install maven
    ansible.builtin.yum:
      name: maven
      state: present
  - name: Application setup
    ansible.builtin.import_role:
      name: common
      tasks_from: app_setup
  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app/
  - name: move jar file from target directory
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app
  - name: load schema into mysql
    ansible.builtin.import_role:
      name: common
      tasks_from: load_mysql_schema
  - name: copy,reload,start and enable service
    ansible.builtin.import_role:
      name: common
      tasks_from: service_en&start
  

  
